(cl:in-package bench-msg)
(cl:export '(FLEX_MYOBRICK_PWM-VAL
          FLEX_MYOBRICK_PWM
          EXTEND_MYOBRICK_PWM-VAL
          EXTEND_MYOBRICK_PWM
          FLEX_MYOBRICK_START-VAL
          FLEX_MYOBRICK_START
          EXTEND_MYOBRICK_START-VAL
          EXTEND_MYOBRICK_START
          RESET_KILL_SWITCH-VAL
          RESET_KILL_SWITCH
          PRESS_KILL_SWITCH-VAL
          PRESS_KILL_SWITCH
))