(cl:in-package bench-msg)
(cl:export '(ANGLE-VAL
          ANGLE
          SAFETY_SWITCH_PRESSED-VAL
          SAFETY_SWITCH_PRESSED
          FLEX_MYOBRICK_POS_ENCODER-VAL
          FLEX_MYOBRICK_POS_ENCODER
          FLEX_MYOBRICK_TORQUE_ENCODER-VAL
          FLEX_MYOBRICK_TORQUE_ENCODER
          FLEX_MYOBRICK_CURRENT-VAL
          FLEX_MYOBRICK_CURRENT
          FLEX_MYOBRICK_PWM-VAL
          FLEX_MYOBRICK_PWM
          FLEX_MYOBRICK_IN_RUNNING_STATE-VAL
          FLEX_MYOBRICK_IN_RUNNING_STATE
          EXTEND_MYOBRICK_POS_ENCODER-VAL
          EXTEND_MYOBRICK_POS_ENCODER
          EXTEND_MYOBRICK_TORQUE_ENCODER-VAL
          EXTEND_MYOBRICK_TORQUE_ENCODER
          EXTEND_MYOBRICK_CURRENT-VAL
          EXTEND_MYOBRICK_CURRENT
          EXTEND_MYOBRICK_PWM-VAL
          EXTEND_MYOBRICK_PWM
          EXTEND_MYOBRICK_IN_RUNNING_STATE-VAL
          EXTEND_MYOBRICK_IN_RUNNING_STATE
))